name: Build and deploy React to deploy-build branch

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build React app
        run: npm run build

      - name: Verify build output
        run: |
          if [ ! -d "build" ]; then
            echo "Build failed: build/ folder not found"
            exit 1
          else
            ls -la build
          fi

      - name: Prepare deploy-build branch
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git checkout -B deploy-build
          git rm -rf . || true
          cp -r build/* .
          rm -rf build
          touch .nojekyll
          git add .
          git commit -m "Deploy React build [skip ci]" || echo "No changes to commit"

      - name: Push to deploy-build branch
        run: git push -f origin deploy-build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
